### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by Pomax** [AppliedMathematicsANU/plexus-form#23]
Since "read the code" is usually not the best recommendation, could a rudimentary tutorial be added to the README.md? Just some simple "this is the boiler plate, here are the supported element types, here's a simple jsx with "complex" form that does some things"?

**Comment by odf** [comment]
That's a very reasonable request.

**Comment by bebraw** [comment]
I have a nice setup for this at [reactabular](https://github.com/bebraw/reactabular). Basically I set it up so that it generates `gh-pages` site based on the project README and demo. It is possible to develop the demo interactively (hot loading).

If you want, I can set this up for you. The approach is much cleaner than the earlier one (no need to maintain a build directory for the demo at the master branch itself). The tooling outputs a .gitignored directory that will be deployed using a specific command.

**Comment by odf** [comment]
That sounds great.

**Comment by odf** [comment]
I've added some basic documentation and deployed the demo site using @bebraw's setup. Not all features are covered yet, but it should be a starting point.

**Comment by odf** [comment]
Oh, and I guess I'll leave this here open until the doco is reasonably complete.

**Comment by odf** [comment]
Ah, I just looked through it and realised I forgot to document how to add CSS classes to fields and sections, and how to switch between alternative sections within a `oneOf`. I will probably get to that tomorrow. I should also clarify that the list of supported JSON-Schema properties refers to what's built into plexus-form and does not cover al the additional predicates that plexus-validate can check.

If there are other things you think are important to get into the documentation right away, let me know.

**Comment by Pomax** [comment]
nice, thank you so much! shall I just open a new issue if I run into things that feel missing instead of keeping this one open?

**Comment by odf** [comment]
@Pomax Yes, good idea! Separate issues will be easier to track.

**Comment by odf** [comment]
I've added the missing pieces of documentation mentioned above, so I'll close this issue now.
